# Generated by Django 3.2.3 on 2021-05-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='zzz_permanent_values',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('installed_date', models.CharField(max_length=50, null=True)),
                ('currency', models.CharField(max_length=50, null=True)),
                ('header', models.CharField(max_length=250, null=True)),
                ('footer', models.CharField(max_length=250, null=True)),
                ('tax', models.FloatField(max_length=50, null=True)),
                ('theme_name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
