# Generated by Django 3.2.3 on 2021-06-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_db', '0003_testdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
